DWAPlannerROS:

#----------------------机器人运动限制参数----------------------------------
  # 最大加速度限制
  acc_lim_x: 0.5
  acc_lim_y: 0.0      # 差速机器人设为0
  acc_lim_th: 2.0     # 角加速度限制

  # 线速度的最大和最小速度
  max_vel_x: 0.3      # 最大前进速度
  min_vel_x: -0.3     # 最大后退速度
  max_vel_y: 0.0      # 差速机器人设为0
  min_vel_y: 0.0      # 差速机器人设为0

  # 旋转的最大和最小角速度
  max_vel_theta: 2.094  # 最大角速度，120度/秒 = 2.094弧度/秒
  min_vel_theta: -2.094 # 最小角速度，-120度/秒 = -2.094弧度/秒

  # 定义了机器人停止时的平移速度和角速度阈值,当机器人的平移速度（即线速度）
  # 旋转速度（即角速度）低于这个值时，规划器会认为机器人已经停止。
  # 这个参数的设置是为了避免机器人因为微小的速度波动而被误认为仍在移动。
  trans_stopped_vel: 0.02
  theta_stopped_vel: 0.05

  # 定义了机器人平移的最大和最小速度的绝对值。定义了机器人平移速度的最值，
  # 即机器人在平面内移动时的最大合成速度（不考虑方向）。
  # max_vel_x、min_vel_x、max_vel_y、min_vel_y这些参数是分方向的速度限制，
  # 这个参数非常好！意味着小车可以避免在难控制区控制速度！！！！！！！！点赞！！！！！
  max_vel_trans: 0.5
  min_vel_trans: 0.05  # 最小平移速度

#---------------------------目标容差参数----------------------------------
# 这些参数控制机器人到达目标点时的精度。
  yaw_goal_tolerance: 0.2  # 约10度 定义了机器人到达目标点时，偏航角的允许误差（单位：弧度）。
  xy_goal_tolerance: 0.3    # 定义了机器人到达目标点时，在 xy 平面内与目标点的距离误差。
  latch_xy_goal_tolerance: true #如果设置为 true，当机器人进入容错距离后，即使旋转时跑出容错距离，也会继续旋转直到达到目标方向。

#---------------------------前向仿真参数----------------------------------
# 这些参数影响规划器生成轨迹的精度和计算复杂度
  # 定义了规划器向前仿真轨迹的时间长度。sim_time 较大：规划器会生成更长的轨迹，
  # 能够更好地预测机器人的未来运动。适合机器人需要长距离规划的场景（例如空旷环境）。
  # 但计算量会增加，可能会导致规划器响应变慢。sim_time 较小：规划器生成的轨迹较短，
  # 计算量较小，响应更快。适合机器人需要快速调整路径的场景（例如狭窄或动态环境）。
  # 但可能会因为轨迹太短而无法有效避开障碍物或接近目标。
  sim_time: 1.5          # 增加仿真时间
  # 定义了轨迹上采样点之间的距离，影响轨迹的密集程度。规划器在生成轨迹时，会将轨迹离散化为多个采样点，
  # 每个采样点之间的距离由 sim_granularity 决定。通过调整 sim_granularity，
  # 可以控制轨迹的精度和计算量。sim_granularity = 0.05，轨迹上每 0.05 米会有一个采样点。
  sim_granularity: 0.05
  # vx_samples、vy_samples 和 vth_samples 是用于控制速度空间采样的参数。
  # 它们决定了在速度空间中采样的点数，进而影响规划器生成轨迹的精度和计算复杂度。
  # 速度空间采样点数是指在DWA算法的第一步中，在速度空间中采样的速度组合的数量。
  # 采样点数越多，生成的速度组合越多，轨迹的多样性也越强，但计算量也会相应增加。
  vx_samples: 20
  vy_samples: 0          # 差速机器人设为0
  vth_samples: 40

  controller_frequency: 3.0 # 控制频率，与move_base设置相同

#---------------------------轨迹评分参数----------------------------------
#  path_distance_bias: 40.0  # 32.0  该参数定义了轨迹与全局路径的接近程度的权重。当 path_distance_bias 值较大时，规划器会更倾向于选择与全局路径接近的轨迹。这个参数用于确保机器人尽可能沿着全局规划器生成的路径移动，而不是偏离太远。如果机器人经常偏离全局路径，可以适当增加该值。如果机器人过于死板地跟随全局路径而无法避障，可以适当减小该值。
#  goal_distance_bias: 24.0  # 24.0  该参数定义了轨迹与局部目标点接近程度的权重。当 goal_distance_bias 值较大时，规划器会更倾向于选择能够更快到达目标点的轨迹。这个参数用于确保机器人能够高效地朝着目标点移动。如果机器人到达目标点的速度较慢，可以适当增加该值。如果机器人过于追求快速到达目标点而忽略了避障或路径平滑性，可以适当减小该值。goal_distance_bias 参数定义的是轨迹与局部目标点接近程度的权重，而局部目标点通常是全局路径规划器（如 global_planner 或 navfn）生成的路径上的某个点，或者是路径的终点（即最终目标点）。这个参数的作用是让 DWA 局部规划器在评估轨迹时，优先选择那些能够更快接近目标点的轨迹。
#  occdist_scale: 1.5     # 0.01   该参数定义了轨迹避障的权重。当 occdist_scale 值较大时，规划器会更倾向于选择远离障碍物的轨迹。如果机器人经常撞到障碍物，可以适当增加该值。如果机器人过于保守，总是远离障碍物而导致路径不够平滑，可以适当减小该值。
#  forward_point_distance: 0.325 # 0.325 该参数定义了在轨迹前方多远的位置放置一个额外的评分点。通过在轨迹前方放置一个额外的评分点，规划器可以更好地评估轨迹的前方状态，从而避免机器人进入危险区域。如果机器人经常进入危险区域，可以适当增加该值。如果机器人过于保守，导致路径不够高效，可以适当减小该值。
#  stop_time_buffer: 0.2     # 0.2  该参数定义了机器人在碰撞前必须提前停止的时间长度。
#  scaling_speed: 0.25     # 0.25  这个参数用于提高机器人在高速运动时的安全性。
#  max_scaling_factor: 0.2   # 0.2   这个参数用于确保机器人在高速运动时有足够的安全距离。
#  publish_cost_grid: false  # 该参数定义了是否发布规划器在规划路径时的代价网格。如果设置为 true，规划器会在 ~/cost_cloud 话题上发布代价网格信息，通常用于调试和可视化。代价网格显示了规划器在评估轨迹时对每个网格单元的评分。

  #重点调整参数！！！
  path_distance_bias: 50.0  # 轨迹与全局路径的接近程度的权重
  goal_distance_bias: 25.0  # 轨迹与局部目标点接近程度的权重 可提升到30
  occdist_scale: 0.5        # 轨迹避障的权重

  forward_point_distance: 0.2 # 在轨迹前方多远的位置放置一个额外的评分点，避免机器人进入危险区域
  stop_time_buffer: 0.3
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  publish_cost_grid: true

#---------------------------振荡预防参数----------------------------------
  oscillation_reset_dist: 0.02
#  hdiff_scale: 1.0 # 是一个与 航向角（heading）偏差(航向角是指机器人当前朝向与目标方向之间的角度偏差。)相关的参数。它用于控制机器人在路径规划时对目标方向偏差的敏感度。值越大，机器人越倾向于调整航向角以减少偏差。值越小，机器人对航向角偏差的敏感度越低。
#  heading_points: 1 # 参数定义了在路径规划时，机器人需要考虑的路径点的数量，用于计算方向.heading_points 决定了机器人在规划路径时，会考虑多少个路径点来计算其目标方向。设置为 1 表示机器人只考虑下一个路径点的方向。增加这个值会使机器人在规划时考虑更远的路径点，从而可能使路径更加平滑。

#---------------------------全局路径参数----------------------------------
  prune_plan: true  # 如果设置为 true，机器人会在前进时清除身后 1 米外的轨迹，减少不必要的路径点

#---------------------------其他参数-------------------------------------
  publish_traj_pc: true # 是否发布规划器在规划路径时的代价网格。
  publish_cost_grid_pc: true  # 这个参数控制是否发布规划器在规划路径时的代价网格点云（cost grid point cloud）。
  global_frame_id: map  # 定义了全局坐标系，通常为 map。